<?php

namespace ChurchTools\Api2\Normalizer;

class NormalizerFactory
{
    public static function create()
    {
        $normalizers = array();
        $normalizers[] = new \Symfony\Component\Serializer\Normalizer\ArrayDenormalizer();
        $normalizers[] = new PersonNormalizer();
        $normalizers[] = new PersonPrivacyPolicyAgreementNormalizer();
        $normalizers[] = new PersonSettingNormalizer();
        $normalizers[] = new GroupNormalizer();
        $normalizers[] = new GroupInformationNormalizer();
        $normalizers[] = new GroupSettingsNormalizer();
        $normalizers[] = new GroupSettingsGroupMeetingNormalizer();
        $normalizers[] = new GroupSettingsNewMemberNormalizer();
        $normalizers[] = new GroupFollowUpNormalizer();
        $normalizers[] = new GroupRolesItemNormalizer();
        $normalizers[] = new RoleNormalizer();
        $normalizers[] = new GroupMemberNormalizer();
        $normalizers[] = new StatusNormalizer();
        $normalizers[] = new CampusNormalizer();
        $normalizers[] = new ServiceGroupNormalizer();
        $normalizers[] = new ServiceNormalizer();
        $normalizers[] = new TagNormalizer();
        $normalizers[] = new DepartmentNormalizer();
        $normalizers[] = new FileNormalizer();
        $normalizers[] = new LogNormalizer();
        $normalizers[] = new AppointmentTemplateNormalizer();
        $normalizers[] = new AgendaNormalizer();
        $normalizers[] = new AgendaItemsItemNormalizer();
        $normalizers[] = new AgendaItemsItemResponsibleNormalizer();
        $normalizers[] = new AgendaItemsItemResponsiblePersonsItemNormalizer();
        $normalizers[] = new AgendaItemsItemServiceGroupNotesItemNormalizer();
        $normalizers[] = new AgendaItemsItemSongNormalizer();
        $normalizers[] = new EventNormalizer();
        $normalizers[] = new EventEventServicesItemNormalizer();
        $normalizers[] = new InfoGetResponse200Normalizer();
        $normalizers[] = new WhoamiGetResponse200Normalizer();
        $normalizers[] = new CampusesGetResponse200Normalizer();
        $normalizers[] = new CampusesGetResponse200MetaNormalizer();
        $normalizers[] = new CampusesPostBodyNormalizer();
        $normalizers[] = new CampusesPostResponse201Normalizer();
        $normalizers[] = new CampusesPostResponse201MetaNormalizer();
        $normalizers[] = new CampusesIdGetResponse200Normalizer();
        $normalizers[] = new CampusesIdPutBodyNormalizer();
        $normalizers[] = new CampusesIdPutResponse200Normalizer();
        $normalizers[] = new FieldsGetResponse200Normalizer();
        $normalizers[] = new FieldsGetResponse200DataItemNormalizer();
        $normalizers[] = new FieldsGetResponse200MetaNormalizer();
        $normalizers[] = new StatusesGetResponse200Normalizer();
        $normalizers[] = new StatusesGetResponse200MetaNormalizer();
        $normalizers[] = new StatusesPostBodyNormalizer();
        $normalizers[] = new StatusesPostResponse201Normalizer();
        $normalizers[] = new StatusesPostResponse201MetaNormalizer();
        $normalizers[] = new StatusesIdGetResponse200Normalizer();
        $normalizers[] = new StatusesIdPutBodyNormalizer();
        $normalizers[] = new StatusesIdPutResponse200Normalizer();
        $normalizers[] = new PersonsGetResponse200Normalizer();
        $normalizers[] = new PersonsGetResponse200MetaNormalizer();
        $normalizers[] = new PersonsPostBodyNormalizer();
        $normalizers[] = new PersonsPostBodyPrivacyPolicyAgreementNormalizer();
        $normalizers[] = new PersonsPostResponse200Normalizer();
        $normalizers[] = new PersonsPostResponse400Normalizer();
        $normalizers[] = new PersonsPropertiesPostBodyNormalizer();
        $normalizers[] = new PersonsPropertiesPostResponse200Normalizer();
        $normalizers[] = new PersonsPropertiesPostResponse200DataNormalizer();
        $normalizers[] = new PersonsPropertiesPostResponse200Data1Normalizer();
        $normalizers[] = new PersonsIdGetResponse200Normalizer();
        $normalizers[] = new PersonsIdPatchResponse200Normalizer();
        $normalizers[] = new PersonsIdPatchResponse400Normalizer();
        $normalizers[] = new PersonsIdTagsGetResponse200Normalizer();
        $normalizers[] = new PersonsIdRelationshipsGetResponse200Normalizer();
        $normalizers[] = new PersonsIdRelationshipsGetResponse200DataItemNormalizer();
        $normalizers[] = new PersonsIdSettingsGetResponse200Normalizer();
        $normalizers[] = new PersonsIdSettingsModuleGetResponse200Normalizer();
        $normalizers[] = new PersonsIdSettingsModuleAttributeGetResponse200Normalizer();
        $normalizers[] = new PersonsIdSettingsModuleAttributePutResponse200Normalizer();
        $normalizers[] = new PersonsIdEventsGetResponse200Normalizer();
        $normalizers[] = new GroupsGetResponse200Normalizer();
        $normalizers[] = new GroupsGetResponse200MetaNormalizer();
        $normalizers[] = new GroupsIdGetResponse200Normalizer();
        $normalizers[] = new GroupsIdMembersGetResponse200Normalizer();
        $normalizers[] = new GroupsIdMembersGetResponse200MetaNormalizer();
        $normalizers[] = new ServicegroupsGetResponse200Normalizer();
        $normalizers[] = new ServicesGetResponse200Normalizer();
        $normalizers[] = new TagsPostBodyNormalizer();
        $normalizers[] = new TagsPostResponse200Normalizer();
        $normalizers[] = new DepartmentsGetResponse200Normalizer();
        $normalizers[] = new DepartmentsGetResponse200MetaNormalizer();
        $normalizers[] = new FilesDomainTypeDomainIdentifierPostBodyNormalizer();
        $normalizers[] = new FilesDomainTypeDomainIdentifierPostResponse200Normalizer();
        $normalizers[] = new FilesDomainTypeDomainIdentifierPostResponse200MetaNormalizer();
        $normalizers[] = new LogsGetResponse200Normalizer();
        $normalizers[] = new LogsGetResponse200MetaNormalizer();
        $normalizers[] = new LogsGetResponse200MetaPaginationNormalizer();
        $normalizers[] = new LogsIdGetResponse200Normalizer();
        $normalizers[] = new CalendarsAppointmentsTemplatesGetResponse200Normalizer();
        $normalizers[] = new CalendarsAppointmentsTemplatesPostBodyNormalizer();
        $normalizers[] = new CalendarsAppointmentsTemplatesPostResponse200Normalizer();
        $normalizers[] = new CalendarsAppointmentsTemplatesTemplateIdGetResponse200Normalizer();
        $normalizers[] = new CalendarsAppointmentsTemplatesTemplateIdPutResponse200Normalizer();
        $normalizers[] = new EventsEventIdAgendaGetResponse200Normalizer();
        $normalizers[] = new AgendasSendPostBodyNormalizer();
        $normalizers[] = new AgendasSendPostResponse200Normalizer();
        $normalizers[] = new AgendasSendPostResponse200ArgsNormalizer();
        $normalizers[] = new AgendasSendPostResponse200ErrorsItemNormalizer();
        $normalizers[] = new AgendasSendPostResponse200ErrorsItemDomainAttributesNormalizer();
        $normalizers[] = new MasterdataPersonRolesGetResponse200Normalizer();
        $normalizers[] = new MasterdataPersonRolesGetResponse200MetaNormalizer();
        $normalizers[] = new MasterdataPersonRolesRoleIdGetResponse200Normalizer();
        return $normalizers;
    }
}
